[package]
name = "shellexpand"
version = "1.1.1"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Shell-like expansions in strings"
repository = "https://github.com/netvl/shellexpand"
documentation = "http://netvl.github.io/shellexpand/"
readme = "Readme.md"
keywords = ["strings", "shell", "variables"]
edition = "2018"

[dependencies]
dirs = "2.0"

[target.'cfg(any(target_os = "dragonfly", target_os = "freebsd", target_os = "linux", target_os = "netbsd", target_os = "openbsd", target_os = "macos"))'.dependencies]
libc = "0.2"
